---
- name: create dir
  file:
    dest: '{{sap_ase_home}}/install'
    state: directory
    owner: sybase
    group: sybase

- name: copy file-install
  unarchive:
    src: '{{sap_ase_path2tar}}'
    dest: '{{sap_ase_home}}/install'

- name: fix owner
  file:
    dest: '{{sap_ase_home}}'
    state: directory
    owner: sybase
    group: sybase
    recurse: yes


