- name: verifica se existe o arquivo SYBASE.sh
  stat:
    path: "{{sap_ase_target}}/SYBASE.sh"
  register: instalado_check

- name: install...
  become: yes
  become_user: 'sybase'
  command: >-
    {{sap_ase_home}}/install/setup.bin
    -f {{sap_ase_home}}/install/response
    -i silent
    -DAGREE_TO_SAP_LICENSE=true
  args:
    creates: '{{sap_ase_target}}/SYBASE.sh'
  when: not instalado_check['stat']['exists']|bool
