---
- name: install sudo
  apt:
    name: sudo
    state: latest
    update_cache: yes

- name: create sybase group
  group:
    name: 'sybase'
    state: present

- name: create sybase user
  user:
    name: 'sybase'
    shell: /bin/bash
    skeleton: "/etc/skel"
    home: "{{ sap_ase_home }}"
    group: sybase
    groups: sybase,sudo
    password: "{{sap_ase_password|password_hash('sha512')}}"
    state: present
    append: yes

- name: sybase as sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    insertafter: '^root'
    line: 'sybase ALL=(ALL) NOPASSWD: ALL'
